---
title: "Charts and maps for 9 facts slides, 2024 Update"
output:
  word_document: default
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE,results = FALSE, fig.width = 10, fig.height = 6)
```

# Profile

```{r}

rm(list=ls())

USERNAME    <- Sys.getenv("USERNAME")
USERPROFILE <- Sys.getenv("USERPROFILE")
USER        <- Sys.getenv("USER")

#file paths for each user of the repository
if (USERNAME == "palma"){
  projectFolder  <- file.path(file.path(Sys.getenv("USERPROFILE"), "OneDrive - UNICEF/IDAC/9 facts/Version_2024/output")) #Output files
  repoFolder  <- file.path(file.path(Sys.getenv("USERPROFILE"), "code/Dem-Analytics/08_IDAC_9facts")) #repository files
  rawdataFolder <- file.path(file.path(Sys.getenv("USERPROFILE"), "OneDrive - UNICEF/Migration and Displacement/Data/"))  #raw data folder
} 

# confirm that the main directory is correct
# check if the folders exist
stopifnot(dir.exists(projectFolder))
stopifnot(dir.exists(repoFolder))
```

# Packages and files
```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
library(waffle)
library(hrbrthemes)
library(kableExtra)
library(forcats)
library(scales)
library(ggforce) #for geom_circle plot in fact 7
```

```{r}
addUnits <- function(n) {
  labels <- ifelse(n < 1000, n,  # less than thousands
                   ifelse(n < 1e6, paste0(round(n/1e3), 'k'),  # in thousands
                          ifelse(n < 1e9, paste0(round(n/1e6,1), 'M'),  # in millions
                                 ifelse(n < 1e12, paste0(round(n/1e9,1), 'B'), # in billions
                                        ifelse(n < 1e15, paste0(round(n/1e12), 'T'), # in trillions
                                               'too big!'
                                        )))))
  return(labels)
}
```

# Load data

```{r}
load(file.path(rawdataFolder, "UNPD/WPP2022/wpp_location.Rdata"))
load(file.path(rawdataFolder, "UNPD/WPP2022/UN_MigrantStock.Rdata"))
load(file.path(rawdataFolder, "UNPD/WPP2022/UN_MigrantStockByOriginAndDestination.Rdata"))
load(file.path(rawdataFolder, "UNPD/WPP2022/UN_MigrantStockAge0to17.Rdata")) #country data
load(file.path(rawdataFolder, "UNPD/WPP2022/UN_MigrantStockAge.Rdata")) #country by age groups
load(file.path(rawdataFolder, "UNPD/WPP2022/wpp_age_group.Rdata"))

country_regions <- readr::read_csv(file.path(rawdataFolder,"UNICEF/country_metadata/country_regions_master.csv")) 

load(file.path(rawdataFolder,'UNHCR/GlobalTrends2023/UNHCR_2023.RData'))
load(file.path(rawdataFolder,"IDMC/IDMC2024/idmc_2024.RData"))
load(file.path(rawdataFolder, 'UNRWA/unrwa_refugees.RData'))
load(file.path(rawdataFolder, 'Asylum seekers estimate/AS_estimate_2023.RData'))
```


# FACT 1: Mig Stock
```{r}
mig.stock.0to17 <- mig.stock.0to17 |> mutate(pop.mig.0to17 = pop.mig.0to17.eu)


mig.stock.0to17.wld <- filter(mig.stock.0to17, sex=="both") |>
  select(year, pop.mig.total, pop.mig.0to17) |>
  group_by(year) |>
  summarise_all(sum, na.rm = T) |> 
  mutate(area.id=900) |>
  left_join(subset(mig.stock, sex=="both"&area.id==900, select=c(year, area.id, pop.mig)), by=c("area.id", "year")) |>
  mutate(check=ifelse(pop.mig.total==pop.mig, 1, 0)) # Check if aggregated migrant 0to17 match with migrant stock r data file

pop.mig.0to17.wld <- wpp.age.group |>
  select(area, area.id, year, pop0to17.thsd, poptotal.thsd) |>
  filter(area == "WORLD" & year >= 1990 & year <= 2020) |>
  left_join(select(mig.stock.0to17.wld, area.id, year, pop.mig.0to17, pop.mig), by= c("year", "area.id")) |>
  mutate(mig.0to17.pct = pop.mig.0to17/(pop0to17.thsd*1000)*100,
         mig.pct = pop.mig/(poptotal.thsd*1000)*100) |>
  filter(!is.na(pop.mig))

fig1 <- filter(mig.stock.age, area.id==900 & sex=="both") |>
  select(year:pop.mig) |>
  filter(age.group %in% c("65to69", "70to74", "75plus", "total")) |>
  spread(key=age.group, value=pop.mig) |>
  mutate(`65plus` = `65to69`+`70to74`+`75plus`) |>
  left_join(select(pop.mig.0to17.wld, year, area.id, pop.mig.0to17), by=c("area.id", "year")) |>
  mutate(pop.mig.18to64= total-(pop.mig.0to17+`65plus`)) |>
  select(year:area.id, pop.mig.0to17, pop.mig.18to64, `65plus`) |>
  gather(key=age.group, value=pop.mig, pop.mig.0to17:`65plus`) |>
  mutate(age.group=factor(age.group, levels=c("65plus","pop.mig.18to64","pop.mig.0to17")))

# Plot 
fact1 <- ggplot(fig1, aes(x = factor(year), y = pop.mig / 1000000, fill = age.group)) +
  geom_bar(stat="identity", width = 0.7) +
  geom_text(aes(label = round(pop.mig / 1000000, 0)),position = "stack", colour = "#004d6d", size = 3, fontface="bold", vjust = 1.5, hjust = "center")+
  scale_fill_manual(values = c("#a1dcf8", "#d2da20", "#59b8de"), name="", labels=c("65+", "18 to 64", "Under 18")) +
  scale_x_discrete(breaks=c(1990, 1995, 2000, 2005, 2010, 2015, 2020)) +
 # guides(fill = guide_legend(reverse=TRUE)) +
  theme_classic()+
  theme(axis.line.x = element_line(size=0.5, colour="grey"),
        axis.line.y = element_blank(), 
        axis.title = element_blank(),
        axis.text.x= element_text(size = 8),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "right",
        legend.text = element_text(size = 8))
fact1
ggsave(filename = 'output/fact1.pdf',device = 'pdf')
```  



# FACT 2: Mig Origin-Dest 

```{r}
library(circlize)
orig.dest.region <- mig.stock.orig.dest |>
  filter(year == 2020, dest.area.id < 900,orig.area.id < 900 | orig.area.id == 2003) |>
  select(orig.region, dest.region, pop.mig) |>
  group_by(orig.region, dest.region) |>
  summarize(pop.mig = sum(pop.mig)) |>
  arrange(desc(pop.mig)) |> ungroup()|> mutate(orig.region = replace_na(orig.region, 'Other'), pop.mig = pop.mig/1000000) #origin and destination by major area


pdf(file="outputs/fact2.pdf")


circos.clear()
circos.par(start.degree = 90, canvas.ylim = c(-1.1,1.1), gap.degree = 4, track.margin = c(-0.1, 0.1), points.overflow.warning = FALSE)
par(mar = rep(0.5, 4))

# color palette
# colfunc <- colorRampPalette(c('#0083CF', "white"))
#
# mycolor <- colfunc(length(concerned_ctries)+6)
#mycolor <- mycolor[sample(1:(length(concerned_ctries)+6))]

# Base plot
chordDiagram(
  x = orig.dest.region ,
  grid.col = c("#b21f8c","#29a9e0","#8cc540","#fcda00","grey","#39a443","#e87621"),
  transparency = 0.25,
  directional = 1,
  direction.type = c("arrows", "diffHeight"),
  diffHeight  = -0.04,
  annotationTrack = "grid",
  annotationTrackHeight = c(0.05, 0.1),
  link.arr.type = "big.arrow",
  link.sort = TRUE,
  link.largest.ontop = TRUE)

circos.trackPlotRegion(
  track.index = 1,
  bg.border = NA,
  panel.fun = function(x, y) {

    xlim = get.cell.meta.data("xlim")
    sector.index = get.cell.meta.data("sector.index")

    # Add names to the sector.
    circos.text(
      x = mean(xlim),
      y = 4,
      labels = sector.index,
      facing = "downward",
      niceFacing = T,
      cex = 0.7
    )

    # Add graduation on axis
    circos.axis(
      h = "top",
      major.at = NULL,
      minor.ticks = 1,
      major.tick.percentage = 0.5,
      labels.niceFacing = TRUE,
      labels.cex = 0.5)
  }
)

dev.off()
```  


# FACT 4: Forcibly displaced

```{r}
fact4.idmc <- idmc.stock.2008.2023 |> 
  filter(cause=="Conflict" & sex == "Both sexes") 

## Correcting Gaza  2023 --------------------------------------------------------------------------------------------------------------
#IDMC estimates that in 2023, 70% of IDPs in Gaza are also registered as UNRWA refugees
# To correct for this, we remove these registered refugees from IDMC numbers by conflict
# We only keep 30% of the numbers from PSE in 2023.
# Because IDMC uses 3 groups for 0-17 data, we remove 70% from all groups

# See: https://www.unhcr.org/refugee-statistics/insights/explainers/forcibly-displaced-pocs.html (Acessed on 2024-06-28)
# Website saved as PDF in Migration and Displacement\Data\IDMC\IDMC2024\UNRWA Refugees in IDMC data 2023 Correction.pdf
fact4.idmc[fact4.idmc$year==2023 & fact4.idmc$iso3 == "PSE",5:11] <- fact4.idmc[fact4.idmc$year==2023 & fact4.idmc$iso3 == "PSE",5:11]*.3

# fact4.idmc.disaster <- idmc.stock.2008.2023 |> 
#   filter(cause=="Disaster" & sex == "Both sexes", year == 2023) |> 
#   group_by(year)|> 
#   summarise(pop = sum(idp.stock, na.rm = T),
#             pop.0to17 = sum(idp.stock.0to17, na.rm = T)) |> 
#   mutate(pop.type = "Disaster-related\ninternally displaced children") |> 
#   select(year, pop.type, pop, pop.0to17) 


fact4.idmc <- fact4.idmc|> 
  group_by(year)|> 
  summarise(pop = sum(idp.stock, na.rm = T),
            pop.0to17 = sum(idp.stock.0to17, na.rm = T)) |> 
  mutate(pop.type = "Conflict-related\ninternally displaced children") |> 
  select(year, pop.type, pop, pop.0to17) 

fact4.unrwa <- unrwa.refugees |> 
  mutate(pop.all = pop*(age=="all"),
         pop.0to17 = pop*(age=="0to17")) |> 
  filter(is.na(iso3)) |> 
  group_by(year) |> 
  summarise(pop = sum(pop.all),
            pop.0to17 = sum(pop.0to17)) |> 
  mutate(pop.type = 'Palestine refugee children\n(registered with UNRWA)') |> 
  select(year, pop.type, pop, pop.0to17) 

fact4.unhcr <- ref.asylum |> 
  group_by(year)|> 
  summarise(pop = sum(ref, na.rm = T),
            pop.0to17 = sum(ref.0to17.estimate, na.rm = T)) |> 
  mutate(pop.type = "Refugee and other internationally\ndisplaced children (UNHCR)") |> 
  select(year, pop.type, pop, pop.0to17) 

fact4.AS <- AS.estimate |> 
  group_by(year)|> 
  summarise(pop = sum(AS , na.rm = T),
            pop.0to17 = sum(AS.0to17.estimated , na.rm = T)) |> 
  mutate(pop.type = 'Asylum-seeking children') |> 
  select(year, pop.type, pop, pop.0to17) 
  
fact4 <- bind_rows(fact4.idmc,
                   fact4.unhcr,
                   fact4.unrwa,
                   fact4.AS)

fact4.yearly.summary <- fact4 |>
  group_by(year)|> 
  summarise(pop=sum(pop),
            pop.0to17 = sum(pop.0to17),.groups = 'drop') |> 
  mutate(pop.0to17.prop=pop.0to17/pop,
         pop=round(pop/1000000, digits = 1),
         pop.0to17=round(pop.0to17/1000000, digits = 1))

fact4.2023.summary <- fact4 |> filter(year==2023) |> 
  group_by(pop.type) |> 
  summarise(pop.0to17 = sum(pop.0to17),.groups = 'drop')
  

fact4.2010.2017 <- fact4 |> 
  filter(year %in% 2010:2017) |> 
  group_by(year) |>
  summarise(pop.0to17 = sum(pop.0to17)) |> 
  mutate(pop.type = 'Total forcibly displaced children')

fact4.2018.plus <- fact4 |> 
  filter(year >=2018) 

fact4.total.label <- fact4 |> 
  filter(year>=2010) |> 
  group_by(year) |>
  summarise(pop.0to17 = sum(pop.0to17)) |> 
  mutate(pop.type="Total")

fact4_new <- bind_rows(fact4.2010.2017, fact4.2018.plus)
fact4_new$pop.label <- fact4_new$pop.0to17
fact4_new$pop.label[fact4_new$year < 2018] <- NA

#order of labels
fact4_new$pop.type <- factor(fact4_new$pop.type, levels = c('Total forcibly displaced children', 
                                                            "Conflict-related\ninternally displaced children",
                                                            'Asylum-seeking children',
                                                            "Refugee and other internationally\ndisplaced children (UNHCR)",
                                                            'Palestine refugee children\n(registered with UNRWA)'))

cols <- c('Total forcibly displaced children' = '#0092C4', 
          "Conflict-related\ninternally displaced children" = '#774C9E',
          'Asylum-seeking children' = "#E60037",
          "Refugee and other internationally\ndisplaced children (UNHCR)" = "#FDC200",
          'Palestine refugee children\n(registered with UNRWA)' = '#39A443')

# Plot 
fact4.fig <- ggplot(fact4_new, aes(x = factor(year), y = pop.0to17 / 1000000, fill = pop.type)) +
  geom_bar(stat="identity", width = 0.5) +
  geom_text(data = fact4_new, 
            mapping = aes(label = round(pop.label / 1000000, 1), y = pop.0to17/1000000), 
            colour = "white",size = 3, fontface="bold",
            position = position_stack(vjust = 0.5))+
  geom_text(data = fact4.total.label, 
            mapping = aes(label = round(pop.0to17 / 1000000, 1), y = pop.0to17/1000000, fill = NA), 
            colour = "#0092C4", size = 4, fontface="bold", vjust=-.3)+
  scale_fill_manual(values = cols,
                    name = '') +
  scale_x_discrete(breaks=2010:2023) +
  scale_y_continuous(limits = c(0,50)) +
  labs(x = NULL, y = NULL)+
  theme_classic() +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))+
  theme(axis.line = element_line(colour = 'grey50', size = 0.4),
        axis.text = element_text(size = 8, color = 'grey50'), 
        axis.ticks = element_line(colour = 'grey50', size = 0.4), 
        axis.title = element_text(size = 8, color = 'grey50'),
        legend.position="bottom", 
        legend.title=element_blank(), 
        plot.title = element_text(color = '#0092C4'),
        plot.subtitle = element_text(color = '#0092C4'))

print(fact4.fig)
ggsave(filename = file.path(projectFolder, 'fact4.pdf'),
       device = 'pdf', width = 20, height = 20, units = "cm")
```



# FACT 5: Refugee Origin

```{r}
fact5 <- ref.origin |> 
  filter(year==2023) |> 
  filter(!(iso3 %in% c("UNK", "XXA", "TIB", "LUX", "PLW")) ) |> 
  select(iso3, ref.0to17.estimate) |> 
  left_join(country_regions |> select(iso3, country_abbr, sdgregion), by='iso3')

fact5$country.label <- fact5$country_abbr
fact5$country.label[fact5$ref.0to17.estimate<100000] <- NA
fact5$country.label[fact5$country.label == "Democratic Republic of the Congo"] <- "DRC"
fact5$country.label[fact5$country.label == "Central African Republic"] <- "CAR"
fact5$country.label[fact5$country.label == "Syrian Arab Republic"] <- "Syria"

fact5_toView <- fact5 |>
  arrange(desc(ref.0to17.estimate)) |> 
  mutate(ref.0to17.estimate.perc = 100*ref.0to17.estimate/sum(ref.0to17.estimate),
         cumul.perc = round(cumsum(ref.0to17.estimate.perc)),
         ref.0to17.estimate.perc = round(ref.0to17.estimate.perc),
         ref.0to17.estimate.thousands=round(signif(ref.0to17.estimate, digits = 2)),
         ref.0to17.estimate = round(ref.0to17.estimate / 1000000, digits = 1)) 

View(fact5_toView)

```

## FACT 5: Refugee Origin: Region
```{r}
fact5_toView_region <- fact5 |>
  group_by(sdgregion) |> 
  summarise(ref.0to17.estimate=sum(ref.0to17.estimate)) |> 
  arrange(desc(ref.0to17.estimate)) |> 
  mutate(ref.0to17.estimate.perc = 100*ref.0to17.estimate/sum(ref.0to17.estimate),
         ref.0to17.estimate.millions = round(ref.0to17.estimate / 1000000, digits = 1))

View(fact5_toView_region)

#Syria percentage from Northern Africa and Western Asia
round(100*2881392.4500/3902425.783)

#Afghanistan percentage from Central and Southern Asia
round(100*3142712.7500/3265533.697)

#Ukraine percentage from Europe and Northern America
round(100*1873858.3875/1925225.258)

#################
fact5_toView_ssa <- fact5 |> filter(sdgregion=="Sub-Saharan Africa")|>
  arrange(desc(ref.0to17.estimate)) |> 
  mutate(ref.0to17.estimate.perc = 100*ref.0to17.estimate/sum(ref.0to17.estimate),
         cumul.perc = round(cumsum(ref.0to17.estimate.perc)),
         ref.0to17.estimate.perc = round(ref.0to17.estimate.perc),
         ref.0to17.estimate.thousands=round(signif(ref.0to17.estimate, digits = 2)),
         ref.0to17.estimate = round(ref.0to17.estimate / 1000000, digits = 1)) 

View(fact5_toView_ssa)

#total in SSA in millions 3703935.107

```


## FACT 5: Refugee Origin: Chart

```{r}
library(igraph)
library(ggraph)

region_colors <- tibble(color_region=c("#EDA877","#EDA87770",
                                       "#8C789E","#8C789E70",
                                       "#7FBA70","#7FBA7070",
                                       "#EAE8FF","#EAE8FF70",
                                       "#62ABC3","#62ABC370",
                                       "#C978CF","#C978CF70",
                                       "#E6738E","#E6738E70",
                                       "#FEE07F","#FEE07F70",
                                       "#FFFFFF"),
                        sdgregion=c("Eastern and South-Eastern Asia",
                                    "XEastern and South-Eastern Asia",
                                    "Central and Southern Asia",
                                    "XCentral and Southern Asia",
                                    "Latin America and the Caribbean",
                                    "XLatin America and the Caribbean",
                                    "Northern Africa and Western Asia",
                                    "XNorthern Africa and Western Asia",
                                    "Europe and Northern America",
                                    "XEurope and Northern America",
                                    "Oceania (excluding Australia and New Zealand)",
                                    "XOceania (excluding Australia and New Zealand)",
                                    "Sub-Saharan Africa",
                                    "XSub-Saharan Africa",
                                    "Australia and New Zealand",
                                    "XAustralia and New Zealand",
                                    "World"))

my_colors2 <- region_colors$color_region
names(my_colors2) <- region_colors$sdgregion


df <- data_frame(group = fact5$sdgregion,
                 subgroup = fact5$country_abbr)
#adding rows of regional levels
df <- bind_rows(df, tibble(group=rep("World", length(region_colors$sdgregion[c(1,3,5,7,9,11,13,15)])),
                           subgroup=region_colors$sdgregion[c(1,3,5,7,9,11,13,15)]))

df <- as.data.frame(table(df))
df <- filter(df, Freq > 0)

#the size of circle should be stored in the vertices object
vertices <- df |>
  dplyr::distinct(subgroup, Freq) |>
  dplyr::add_row(subgroup = "World", Freq = 0)|> 
  left_join(fact5  |> select(country_abbr, ref.0to17.estimate, sdgregion), by=c("subgroup" ="country_abbr"))
  
vertices$ref.0to17.estimate[is.na(vertices$ref.0to17.estimate)] <- 0  #fill NA values of regions

#region category names for special coloring
vertices$sdgregion[vertices$subgroup=="Sub-Saharan Africa"] <- "XSub-Saharan Africa"
vertices$sdgregion[vertices$subgroup=="Northern Africa and Western Asia"] <- "XNorthern Africa and Western Asia"
vertices$sdgregion[vertices$subgroup=="Central and Southern Asia"] <- "XCentral and Southern Asia"
vertices$sdgregion[vertices$subgroup=="Eastern and South-Eastern Asia"] <- "XEastern and South-Eastern Asia"
vertices$sdgregion[vertices$subgroup=="Europe and Northern America"] <- "XEurope and Northern America"
vertices$sdgregion[vertices$subgroup=="Latin America and the Caribbean"] <- "XLatin America and the Caribbean"
vertices$sdgregion[vertices$subgroup=="Australia and New Zealand"] <- "XAustralia and New Zealand"
vertices$sdgregion[vertices$subgroup=="Oceania (excluding Australia and New Zealand)"] <- "Oceania (excluding Australia and New Zealand)"
vertices$sdgregion[vertices$subgroup=="World"] <- "World"

#selecting which countries to show label
min.pop.label <- 150000
vertices$name_label <- NA
vertices$name_label[!is.na(vertices$ref.0to17.estimate) & vertices$ref.0to17.estimate>min.pop.label] <- vertices$subgroup[!is.na(vertices$ref.0to17.estimate) & vertices$ref.0to17.estimate>min.pop.label]
vertices$name_label[vertices$name_label == "Central African Republic"] <- "CAR"
vertices$name_label[vertices$name_label == "Venezuela (Bolivarian Republic of)"] <- "Venezuela\n(Bol. Rep. of)"
vertices$name_label[vertices$name_label == "Syrian Arab Republic"] <- "Syrian\nArab\nRep."
vertices$name_label[vertices$name_label == "Democratic Republic of the Congo"] <- "DRC"
vertices$name_label[vertices$name_label == "South Sudan"] <- "South\nSudan"

#region labels
vertices$region_label <- NA
vertices$region_label [vertices$ref.0to17.estimate==0] <- vertices$subgroup[vertices$ref.0to17.estimate==0]
vertices$region_label [vertices$region_label=="World"] <- NA
vertices$ref.0to17.estimate[vertices$ref.0to17.estimate==0] <- 10000 #regional numbers must not be 0. Strange that this is not a problem for asylum

graph <- graph_from_data_frame(df, vertices = vertices)

ggraph(graph, layout = "circlepack", weight = ref.0to17.estimate) +
  geom_node_circle(aes(fill = sdgregion, colour = as.factor(depth), group = depth), 
                   size = 0.01) + #width of circle line
  scale_fill_manual(values=my_colors2, 
                    breaks=region_colors$sdgregion[c(1,3,5,7,9,11,13,15)]) + #adding breaks so the legend only shows the color of the country circles and not the lighter region circles
  coord_fixed() +
  geom_node_text(aes(label = name_label), color = "black", repel = FALSE, size = 1.5, show.legend = F) +
  #geom_node_label(aes(label = region_label), color = "black", repel = TRUE, size = 2, show.legend = F) +
  scale_color_manual( values=c("0" = "white", "1" = "darkgrey", "2" = "darkgrey" ) ) +
  theme_void()+
  guides(colour="none")+
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 3),
        legend.key.size = unit(0.3, "cm"))

ggsave(file.path(projectFolder, "fact5_origin.pdf"), width = 8, height = 5, units='cm')
```



# FACT X Asylum income country
```{r}
data7.income <- unhcr.gt.tab12.new |> 
  filter(area.id < 999) |> 
  filter(pop.type %in% c("Refugees", "Other people in need of international protection")) |> 
  mutate(pop.ref.data.sexage.available = pop.ref.asy*coverage.sex.age.asy) |> #population with known agesex
  left_join(wb.income |> select(iso3, wb.income.2020), by='iso3') |> 
  mutate(pop.ref.data.sexage.available = pop.ref.asy*coverage.sex.age.asy) |>   #population with msex and coverage. Different values for REF and OIP
  group_by(country_abbr) |> 
  summarise(wb.income.2020=unique(wb.income.2020),
            pop.ref = sum(pop.ref.asy, na.rm = T),  #total ref population (REF+OIP)
            pop.ref.data.sexage.available = sum(pop.ref.data.sexage.available), ##population with known agesex, combining REF and OIP
            pop.ref.0to17 = sum(pop.ref.0to17.asy, na.rm = T)) |>   #children population, Only countries with >=0.5 agesex coverage
  mutate(prop.ref.data.sexage.available = pop.ref.data.sexage.available/pop.ref,
         country.label = NA) |> 
  filter(prop.ref.data.sexage.available>=.5) |> 
  select(wb.income.2020, country_abbr, pop.ref.0to17) |> 
  group_by(wb.income.2020) |> 
  summarise(pop.ref.0to17=sum(pop.ref.0to17))

data7.income$prop.ref.0to17 <- data7.income$pop.ref.0to17/sum(data7.income$pop.ref.0to17)

sum(data7.income$prop.ref.0to17[1:2])


```

# FACT 8

```{r}

load(file.path(rawdataFolder, "UNRWA/UNRWA_older/unrwa2021.RData"))
load(file.path(rawdataFolder, 'UNHCR/GlobalTrends2020/unhcr2020.RData'))

#World 2020 mid year population of children, adults and 60+
world.pop <- wpp.age.group |> filter(area == 'WORLD' & year %in% c(2020,2021)) |>
  select( pop0to17 = pop0to17.thsd,poptotal = poptotal.thsd,pop60plus = pop60plus.thsd) |>
  mutate(poptotal = poptotal-pop0to17-pop60plus) |> #adult population
  mutate_all(~.*1000) |>
  select(pop0to17,pop18to59 = poptotal,pop60plus) |>
  sapply(mean)  #mid year. As a mean of 2020 and 2021

#World 2020 migrant population of children, adults and 60+. This includes refugees
mig.pop <- cbind(mig.stock.orig.dest |> filter(year == 2020 & dest.area == 'WORLD') |> distinct(pop.mig.total), age0to17 = mig.stock.0to17.wld |> filter(year == 2020) |> pull(pop.mig.0to17), mig.stock.age |> filter(year == 2020 & area == 'WORLD' & sex =='both' & age.group %in% c('60to64','65to69','70to74','75plus')) |>
  summarise(age60plus = sum(pop.mig))) |>
  mutate(pop.mig.total = pop.mig.total-age0to17-age60plus) |>
  select(pop0to17 = age0to17,pop18to59 = pop.mig.total,pop60plus = age60plus)

#World 2020 UNHCR refugee population of children, adults and 60+. Reminder: this numbers do NOT include UNRWA refugees
ref.pop <- unhcr.gt.tab11 |> #From UNHCR 2020 data
  filter(area.id < 900 & pop.type == 'Refugees') |> 
  filter(coverage.sex.age.asy >= 0.5) |> 
  summarise(sum1 = sum(pop.ref.0to17.fem.asy) + sum(pop.ref.0to17.male.asy),
            sum2 = sum(pop.ref.18to59.fem.asy)+sum(pop.ref.18to59.male.asy),
            sum3 = sum(pop.ref.60plus.fem.asy)+sum(pop.ref.60plus.male.asy)) |>
  mutate(pop0to17 = 20650315*sum1/(sum1+sum2+sum3),
         pop18to59 =20650315* sum2/(sum1+sum2+sum3),
         pop60plus = 20650315*sum3/(sum1+sum2+sum3)) |>  #20650315 is #world refugee 2020
  select(pop0to17, pop18to59 , pop60plus)

#World 2020 UNRWA refugee population of children, adults and 60+. Excluding in Palestine
ref.unrwa.pop.exclpse <- df.unrwa.all.2021 |> 
  filter(year == 2020, !name %in% c("total",'Gaza Strip','West Bank'), age != 'all') |>  
  group_by(age) |>
  summarise(sum(pop)) |> 
  mutate(age = c('pop0to17', 'pop18to59','pop60plus')) |> 
  spread(key = 1, value = 2)

#Adding UNRWA (w/o PSE) to UNHCR refugee. 
ref.pop.all <- ref.pop + ref.unrwa.pop.exclpse

#merging and arranging all tables
fig6<- as.data.frame(rbind(world.pop,mig.pop,ref.pop.all)) |>
  cbind(measure=c('World population','UNPD International\nMigrant Stock','Refugees\n(UNHCR, UNRWA)'))|>
  gather('age','pop',-measure) |>
  group_by(measure) |>
  mutate(pct = pop/sum(pop)) |>
  arrange(measure) |>
  mutate(pct.pos = cumsum(pct)-pct/2)

fact8 <- ggplot(data = fig6,mapping = aes(x = measure, y = pct, fill = age))+
  geom_bar(stat = 'identity', position = position_stack(reverse = TRUE), width = 0.5)+
  scale_y_continuous(labels = scales::percent)+
  geom_text(aes(label = paste0(100*round(pct,2),"%"),y=pct.pos),size = 3, color='white', fontface = "bold")+
  ylab('percent')+
  scale_fill_manual(name = "Age Composition", labels = c("0 to 17", "18 to 59", "60+"), values =  c('#5EBB48','#0092C4','#774C9E'))+
  scale_x_discrete(limits=c('World population','UNPD International\nMigrant Stock','Refugees\n(UNHCR, UNRWA)'))+
  coord_flip()+
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),axis.ticks=element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),plot.background=element_blank(),aspect.ratio = 0.4)
fact8
ggsave('output/fact8.pdf', device = 'pdf')
```  

# FACT 9: Unaccompanied
```{r}
#Eurostat incidator: migr_asyunaa, also in tps00194
#Asylum applicants considered to be unaccompanied minors by citizenship, age and sex - annual data

#Data for 2023, including EU27+EFTA = 40415+15+5+470+2200 


#UK data
#Asy_D01: Asylum applications raised, by nationality, age, sex, UASC, applicant type, and location of application
#https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables#asylum-applications-decisions-and-resettlement
#Data for 2023, 3412
40415+15+5+470+2200 +3412


```


# FACT X: Share of refugees among migrants
We also calculate the share of 0-17 refugees among 0-17 migranbts


```{r}
load(file.path(path.basic, "Data/UNRWA/UNRWA_older/unrwa2021.RData"))
load(file.path(path.basic, 'Data/UNHCR/GlobalTrends2020/unhcr2020.RData'))

mig.stock.0to17 <- mig.stock.0to17 |> mutate(pop.mig.0to17 = pop.mig.0to17.eu)

#UNPD note
# The column labelled “Type of data” indicates the type of data used in deriving the estimates presented. The codes used are: B, which indicates that estimates were derived from data on the foreign-born population; C, which indicates that estimates were derived from data on foreign citizens; R, which indicates that the number of refugees or persons in refugee-like situations, asylum seekers or Venezuelans displaced abroad as reported by the Office of the United Nations High Commissioner for Refugees (UNHCR) or, where appropriate, the United Nations Relief and Works Agency for Palestine Refugees in the Near East (UNRWA) were added to the estimates, and I, which indicates that there were no data on international migrants for the country or area concerned and that the estimates presented were imputed.

#share of refugees among migrants as reported by UNPD

unpd.refugees <- readxl::read_xlsx(file.path(path.basic,'Data/UNPD/UNMigrantStock2020/undesa_pd_2020_ims_stock_by_sex_and_destination.xlsx'),
                                   range='Table 6!B11:S294', #Table 6: Estimated refugee stock (including asylum seekers) at mid-year by region, country or area of destination, 1990-2020
                                   na='~') |> 
  filter(`Location code` <900) |> 
  select('area'="Region, development group, country or area",
         'type.of.data'=`Type of data`,
         'area.id'="Location code",
         'unpd.refugees'='2020...11',
         'unpd.refugees.perc.from.mig.stock'='2020...18') |> 
  mutate(unpd.refugees.perc.from.mig.stock=as.numeric(unpd.refugees.perc.from.mig.stock))  #


#getting the column of type of data for UNPD migrant stock. This was not saved when producing the mig.stock.0-17
mig.stock.0to17.countries.type.of.data <- readxl::read_xlsx(file.path(path.basic,'Data/UNPD/UNMigrantStock2020/undesa_pd_2020_ims_stock_by_age_sex_and_destination.xlsx'),
                                                            range='Table 1!B11:F1992') |> 
  filter(Year==2020) |> 
  select('area.id'="Location code",
         'type.of.data'=`Type of data`)

#UNPD migrant stock. Estimated from undesa_pd_2020_ims_stock_by_age_sex_and_destination.xlsx Table 1.
#Europe countries Corrected using eurostat
mig.stock.0to17.countries <- mig.stock.0to17 |> 
  mutate(pop.mig.0to17 = pop.mig.0to17.eu) |>  #this is correcting the europe numebrs with eurostat data
  filter(year==2020, sex=='both') |> 
  left_join(mig.stock.0to17.countries.type.of.data, by='area.id')

#Countries 2020 UNHCR population of children, adults and 60+. Reminder: this numbers do NOT include UNRWA refugees
#Including Refugees, AS and VDP (after 2022 named OIP)
unhcr.ref <- unhcr.gt.tab11 |> #From UNHCR 2020 data
  filter(area.id < 900 & pop.type %in% c('Refugees', 'Asylum-seekers', 'Venezuelans displaced abroad')) |> 
  group_by(iso3) |> 
  summarise(area.id=unique(area.id),
            ref.unhcr=sum(pop.ref.asy, na.rm=F),
            ref.unhcr.0to17=sum(pop.ref.0to17.asy, na.rm=F)) 
  
#World 2020 UNRWA refugee population of children and total. Excluding in Palestine
unrwa.ref <- df.unrwa.all.2021 |> 
  filter(year == 2020, iso3 %in% c("JOR",'LBN','SYR')) |>  #removing PSE and summaries
  group_by(iso3) |> 
  summarise(ref.unrwa=sum(pop[age=='all']),
            ref.unrwa.0to17=sum(pop[age=='0to17']))

unhcrunrwa.ref <- unhcr.ref |> left_join(unrwa.ref, by='iso3') |> 
  rowwise() |> 
  mutate(unhcrunrwa.ref=sum(ref.unhcr, ref.unrwa, na.rm=T), #na.rm=T because all countries have unhcr or unrwa counts
         unhcrunrwa.ref.0to17=sum(ref.unhcr.0to17, ref.unrwa.0to17, na.rm=F))  #na.rm=F because we can't count children in countries with NA values


#compare refugee numbers from UNPD and UNHCR+UNRWA
#UNPD (2020 mid-year) has 500k less REF+AS+VDA accounted than the numbers from UNHCR and UNRWA (2020 end-year)

unpd.refugees.compare <- unpd.refugees |>
  filter(grepl('R', type.of.data)) |>   #only compare those with UNPD type of data R
  left_join(unhcrunrwa.ref |> select(area.id, unhcrunrwa.ref), by='area.id') |> 
  mutate(difference.from.unhcrunrwa=unpd.refugees - unhcrunrwa.ref ,
         difference.from.unhcrunrwa.perc=(100*(difference.from.unhcrunrwa)/unhcrunrwa.ref))
plot(unpd.refugees.compare$unpd.refugees,unpd.refugees.compare$unhcrunrwa.ref)

#what is the difference? UNPD has 483817 less ref+AS+VDA reported than UNHCR+UNRWA in 2020
sum(unpd.refugees.compare$difference.from.unhcrunrwa, na.rm=T)

#ARE THERE ANY UNPD COUNTIES WITHOUT AN R THAT HAVE SIGNIFICANT UNHCR OR UNRWA POPULATIONS?

#SHARE OF REFUGEES (UNPD OR UNHCR+UNRWA) AMONG UNPD MIGRANT STOCK
share.refugees <- unpd.refugees.compare  |> 
  left_join(mig.stock.0to17.countries |> select(area.id, pop.mig.total, pop.mig.0to17), by='area.id') |> 
  mutate(share.refugees.unpd=round(100*unpd.refugees/pop.mig.total),
         share.refugees.unhcrunrwa=round(100*unhcrunrwa.ref/pop.mig.total),
         difference.from.unhcrunrwa.share=share.refugees.unpd-share.refugees.unhcrunrwa)

big.dif.abs <- share.refugees |> 
  mutate(difference.from.unhcrunrwa.abs=abs(difference.from.unhcrunrwa)) |> 
  arrange(desc(difference.from.unhcrunrwa.abs)) |>
  head(n=10) |> 
  select(area, unpd.refugees, unhcrunrwa.ref, difference.from.unhcrunrwa, share.refugees.unpd, share.refugees.unhcrunrwa)

big.dif.share<- share.refugees |> 
  mutate(difference.from.unhcrunrwa.share.abs=abs(difference.from.unhcrunrwa.share)) |> 
  arrange(desc(difference.from.unhcrunrwa.share.abs)) |>
  head(n=10) |> 
  select(area, unpd.refugees, unhcrunrwa.ref, share.refugees.unpd, share.refugees.unhcrunrwa,difference.from.unhcrunrwa.share)


plot(share.refugees$share.refugees.unpd,share.refugees$share.refugees.unhcrunrwa)

```

